# Generated by Django 5.1.6 on 2025-02-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('conference', 'Conference'), ('business_conference', 'Business Conference'), ('seminar', 'Seminar & Workshop'), ('networking', 'Networking Event'), ('trade_show', 'Trade Show & Expo'), ('agm', 'Annual General Meeting (AGM)'), ('team_building', 'Team Building Activity'), ('product_launch', 'Product Launch'), ('other', 'Other')], max_length=50)),
                ('other_category', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('venue_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('social_media', models.URLField(blank=True, null=True)),
                ('max_attendees', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_pdf', models.FileField(blank=True, null=True, upload_to='event_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
