# Generated by Django 5.1.6 on 2025-03-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seat_booked',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
