# Generated by Django 5.1.6 on 2025-03-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_seat_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seat_booked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
