# Generated by Django 4.2.19 on 2025-02-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='username',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
