# Generated by Django 4.2.19 on 2025-02-18 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_event_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='username',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.user_data'),
        ),
    ]
