# Generated by Django 4.2.19 on 2025-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_event_username_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('conference', 'Conference'), ('business_conference', 'Business Conference'), ('seminar', 'Seminar & Workshop'), ('networking', 'Networking Event'), ('trade_show', 'Trade Show & Expo'), ('agm', 'Annual General Meeting (AGM)'), ('team_building', 'Team Building Activity'), ('product_launch', 'Product Launch'), ('other', 'Other')], default='Workshop', max_length=50),
        ),
    ]
