# Generated by Django 5.1.5 on 2025-02-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=8)),
                ('Re_Password', models.CharField(max_length=8)),
                ('Phone', models.CharField(max_length=10)),
                ('User_type', models.CharField(choices=[('attendee', 'Attendee'), ('organizer', 'Organizer')], default='attendee', max_length=10)),
                ('Company_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Website', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
