# Generated by Django 5.1.5 on 2025-02-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='Username',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='Password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='Re_Password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='User_type',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('organizer', 'Organizer')], default='attendee', max_length=20),
        ),
    ]
