# Generated by Django 5.1.5 on 2025-02-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_data_username_alter_user_data_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='Re_Password',
            field=models.CharField(max_length=50),
        ),
    ]
