# Generated by Django 5.1.5 on 2025-02-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_data_password_alter_user_data_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Password',
            field=models.CharField(max_length=500),
        ),
    ]
